import { useState } from 'react';
import { useApp } from '../store';
import { useBooks } from '../books';
import { Account, AccountGroup, appendJournal, checkDate, inventoryCheck, journalBalance, ledger, monthEnd, statements, today, reverseJournal } from '../lib/accounting';
import { money } from '../lib/finance';
const field='border rounded-lg px-3 py-2 text-sm bg-white';
const box='bg-white border rounded-xl p-4';
const titles={journals:'Jurnal Umum',ledger:'Buku Besar',trial:'Neraca Saldo',statements:'Laporan Keuangan',accounts:'Master Akun / COA'};
export type AccountingPage=keyof typeof titles;
const groupNames:Record<AccountGroup,string>={asset:'Aset',liability:'Liabilitas',equity:'Ekuitas',revenue:'Pendapatan',expense:'Beban'};
export default function Accounting({page}:{page:AccountingPage}) {
  const {state}=useApp(),{book,busy,error,initialize,reload,changeBook,exportBackup,cloud}=useBooks();
  const [month,setMonth]=useState(state.selectedPeriode),[from,setFrom]=useState(state.selectedPeriode+'-01'),[to,setTo]=useState(monthEnd(state.selectedPeriode));
  const [code,setCode]=useState('1000');
  const [start,setStart]=useState('2026-10-01');
  const [show,setShow]=useState(false),[date,setDate]=useState(today()),[description,setDescription]=useState(''),[sourceNumber,setSourceNumber]=useState('');
  const [lines,setLines]=useState([{account:'1000',debit:0,credit:0},{account:'4001',debit:0,credit:0}]);
  const [originalCode,setOriginalCode]=useState<string|null>(null);
  const [localError,setLocalError]=useState(''),[accountEdit,setAccountEdit]=useState<Account|null>(null);
  const canEdit=['admin','finance'].includes(state.currentUser.role),canView=['admin','finance','owner'].includes(state.currentUser.role);
  async function run(action:()=>Promise<void>){setLocalError('');try{await action();}catch(e){setLocalError(e instanceof Error?e.message:'Gagal menyimpan.');}}
  if(!canView)return <p>Akses akuntansi tersedia untuk admin, finance, dan owner.</p>;
  const balance=journalBalance({lines} as Parameters<typeof journalBalance>[0]);
  const report=book?statements(book,from,to):null;
  const bookLedger=book?ledger(book,code,from,to):null;
  const control=book?inventoryCheck(book,to):null;
  return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">{titles[page]}</h1><p className="text-sm text-gray-500">Transaksi → Jurnal → Buku Besar → Laporan Keuangan</p></div><div className="flex gap-2 flex-wrap"><button className={field} disabled={busy} onClick={()=>void run(reload)}>Muat ulang buku</button>{book&&<button className={field} onClick={exportBackup}>Backup stok & akuntansi</button>}{book&&canEdit&&page==='journals'&&<button className="bg-blue-600 text-white px-4 py-2 rounded-lg" disabled={busy} onClick={()=>setShow(true)}>Tambah jurnal</button>}{book&&canEdit&&page==='accounts'&&<button className={field} onClick={()=>{setOriginalCode(null);setAccountEdit({code:'',name:'',group:'expense',normal:'debit',active:true});}}>Tambah akun</button>}</div></div>
    {(error||localError)&&<p role="alert" className="bg-red-50 text-red-800 rounded-xl p-4">{localError||error}</p>}{busy&&<p role="status">Memproses buku…</p>}
    {book&&book.movements.some(m=>m.description==='Harga saldo awal belum diverifikasi'&&!book.movements.some(v=>v.source===`opening-price:${m.id}`))&&<p role="status" className="bg-amber-50 p-4 rounded-xl">Laporan sementara: harga saldo awal persediaan belum lengkap. Nilai nol pada stok belum dinilai bukan harga final. Verifikasi melalui Mutasi Stok.</p>}{!book?<div className={box}><h2 className="font-semibold">Aktifkan buku terintegrasi</h2><p className="text-sm text-gray-600 my-3">Pembukuan dimulai 1 Oktober 2026. Qty snapshot existing dipertahankan; harga lama diabaikan. Verifikasi harga per barang/gudang di Mutasi Stok sebelum posting transaksi stok. Histori transaksi sebelum aktivasi tidak direka ulang. Saldo awal kas, bank, hutang, dan modal perlu diisi melalui jurnal saldo awal dengan bukti sumber.</p><label className="text-sm">Tanggal awal buku <input type="date" className={field} value={start} onChange={e=>setStart(e.target.value)}/></label>{canEdit&&<button disabled={busy} className="ml-3 bg-blue-600 text-white px-4 py-2 rounded-lg" onClick={()=>void run(()=>initialize(start))}>Aktifkan buku</button>}<p className="text-xs text-gray-500 mt-3">{cloud?'Buku digunakan bersama anggota perusahaan di Supabase.':'Mode lokal tersimpan atomik dalam browser ini.'}</p></div>:<>
      <p className="bg-blue-50 rounded-xl p-4 text-sm">Buku mulai {book.cutoff}. Jurnal terposting bersifat tetap; koreksi melalui jurnal pembalik. Saldo awal lengkap harus diverifikasi sebelum laporan dianggap final. {cloud?'Buku perusahaan dibagikan melalui keanggotaan Supabase.':'Mode lokal: backup buku secara berkala.'}</p>
      {page!=='accounts'&&<div className="flex gap-3 flex-wrap items-end"><label className="text-sm">Bulan/tahun<input aria-label="Bulan laporan akuntansi" className={`${field} block`} type="month" value={month} onChange={e=>{setMonth(e.target.value);setFrom(e.target.value+'-01');setTo(monthEnd(e.target.value));}}/></label><label className="text-sm">Dari<input aria-label="Tanggal awal laporan" type="date" className={`${field} block`} value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">Sampai<input aria-label="Tanggal akhir laporan" type="date" className={`${field} block`} value={to} onChange={e=>setTo(e.target.value)}/></label>{page==='ledger'&&<label className="text-sm">Akun<select className={`${field} block`} value={code} onChange={e=>setCode(e.target.value)}>{book.accounts.map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label>}</div>}
      {page!=='accounts'&&(from>to||to<book.cutoff)?<p role="alert" className="bg-amber-50 p-4">Periode tidak valid / mendahului awal buku. Laporan belum tersedia.</p>:<>
      {page==='journals'&&<div className={`${box} overflow-x-auto`}><table className="w-full text-sm text-left"><thead><tr>{['Tanggal','Nomor jurnal','Transaksi sumber','Keterangan','Kode akun','Nama akun','Debit','Kredit'].map(h=><th key={h} className="p-2 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{book.journals.filter(j=>j.date>=from&&j.date<=to).flatMap(j=>j.lines.map((l,i)=><tr key={j.id+'-'+i} className="border-t align-top"><td className="p-2 whitespace-nowrap">{j.date}</td><td className="p-2 whitespace-nowrap">{j.number}{i===0&&canEdit&&!j.reversalOf&&!book.journals.some(x=>x.reversalOf===j.id)&&!j.lines.some(l=>['1200','1300','1301'].includes(l.account))&&<button disabled={busy} className="block text-blue-700 underline text-xs" onClick={()=>{if(confirm(`Buat jurnal pembalik ${j.number} pada tanggal hari ini?`))void run(()=>changeBook(b=>reverseJournal(b,j.id,today(),state.currentUser.nama),'Pembalik jurnal'));}}>Balik jurnal</button>}</td><td className="p-2">{j.sourceNumber}</td><td className="p-2 min-w-56">{j.description}</td><td className="p-2">{l.account}</td><td className="p-2 min-w-40">{book.accounts.find(a=>a.code===l.account)?.name}</td><td className="p-2 whitespace-nowrap">{money(l.debit)}</td><td className="p-2 whitespace-nowrap">{money(l.credit)}</td></tr>))}</tbody></table>{!book.journals.length&&<p className="py-5 text-gray-500">Belum ada jurnal terposting.</p>}</div>}
      {page==='ledger'&&bookLedger&&<div className={`${box} overflow-x-auto`}><p className="mb-3">Saldo awal {money(bookLedger.opening)} · Saldo normal {book.accounts.find(a=>a.code===code)?.normal==='credit'?'kredit':'debit'}</p><table className="w-full text-left text-sm"><thead><tr>{['Tanggal','No jurnal','Keterangan','Debit','Kredit','Saldo'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{bookLedger.rows.map((r,i)=><tr key={i} className="border-t"><td className="p-2 whitespace-nowrap">{r.journal.date}</td><td className="p-2">{r.journal.number}</td><td className="p-2">{r.journal.description}</td><td className="p-2 whitespace-nowrap">{money(r.debit)}</td><td className="p-2 whitespace-nowrap">{money(r.credit)}</td><td className="p-2 whitespace-nowrap">{money(r.balance)}</td></tr>)}</tbody></table><p className="mt-3 font-semibold">Saldo akhir {money(bookLedger.closing)}</p></div>}
      {page==='trial'&&report&&<div className={box}><p className="text-sm text-gray-500 mb-3">Saldo kumulatif buku besar sampai {to}, termasuk jurnal saldo awal.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Kode akun','Nama akun','Debit','Kredit'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{report.trial.map(a=><tr key={a.code} className="border-t"><td className="p-2">{a.code}</td><td className="p-2">{a.name}</td><td className="p-2 whitespace-nowrap">{money(a.debit)}</td><td className="p-2 whitespace-nowrap">{money(a.credit)}</td></tr>)}</tbody></table></div><p className="mt-3 font-semibold">Total debit {money(report.trial.reduce((s,a)=>s+a.debit,0))} · Total kredit {money(report.trial.reduce((s,a)=>s+a.credit,0))}</p><p role="status" className={Math.abs(report.trial.reduce((s,a)=>s+a.debit-a.credit,0))<0.005?'text-green-700':'text-red-700'}>Selisih {money(report.trial.reduce((s,a)=>s+a.debit-a.credit,0))}</p></div>}
      {page==='statements'&&report&&<>
        {report.trial.some(a=>['1109','9991'].includes(a.code)&&a.signed!==0)&&<p role="alert" className="bg-amber-50 text-amber-900 rounded-xl p-4 text-sm">Akun sementara / kliring belum nol. Selesaikan review bank dan pencocokan transfer sebelum laporan difinalkan.</p>}
        <div className="grid md:grid-cols-3 gap-3">{[['Total pendapatan',report.revenue],['Total beban',report.expenses],['Laba/rugi bersih',report.net]].map(([label,n])=><div key={String(label)} className={box}><p className="text-sm text-gray-500">{label}</p><p className="text-xl font-semibold">{money(n as number)}</p></div>)}</div>
        <div className="grid xl:grid-cols-2 gap-4"><div className={box}><h2 className="font-semibold mb-3">Laba rugi ({from} – {to})</h2>{(['revenue','expense'] as AccountGroup[]).map(g=><section key={g}><h3 className="font-semibold mt-4">{groupNames[g]}</h3>{report.lines.filter(a=>a.group===g).map(a=><div key={a.code} className="flex justify-between gap-3 py-2 border-b text-sm"><span>{a.name}</span><span className="whitespace-nowrap">{money(a.amount)}</span></div>)}</section>)}<p className="font-semibold mt-4">Laba/rugi bersih {money(report.net)}</p></div><div className={box}><h2 className="font-semibold mb-3">Neraca / Posisi Keuangan ({to})</h2>{(['asset','liability','equity'] as AccountGroup[]).map(g=><section key={g}><h3 className="font-semibold mt-4">{groupNames[g]}</h3>{report.trial.filter(a=>a.group===g).map(a=><div key={a.code} className="flex justify-between gap-3 py-2 border-b text-sm"><span>{a.name}</span><span className="whitespace-nowrap">{money(g==='asset'?a.signed:-a.signed)}</span></div>)}{g==='equity'&&<div className="flex justify-between text-sm py-2"><span>Laba berjalan kumulatif</span><span>{money(report.cumulativeProfit)}</span></div>}</section>)}<div className="font-semibold text-sm space-y-2 mt-4"><p>Aset {money(report.assets)}</p><p>Liabilitas {money(report.liabilities)} + Ekuitas {money(report.equity)}</p><p role="alert" className={report.difference===0?'text-green-700':'text-red-700'}>Selisih neraca {money(report.difference)}</p></div></div></div>
        {control&&<div className={`${box} ${control.difference===0?'text-green-800':'text-red-800'}`}>Kontrol persediaan: kartu stok {money(control.stock)} · Buku besar 1200 {money(control.gl)} · Selisih {money(control.difference)}</div>}
      </>}
      {page==='accounts'&&<div className={`${box} overflow-x-auto`}><table className="w-full text-left text-sm"><thead><tr>{['Kode','Nama akun','Kelompok','Saldo normal','Status',''].map((h,i)=><th key={i} className="p-2">{h}</th>)}</tr></thead><tbody>{book.accounts.map(a=><tr key={a.code} className="border-t"><td className="p-2">{a.code}</td><td className="p-2">{a.name}</td><td className="p-2">{groupNames[a.group]}</td><td className="p-2">{a.normal==='debit'?'Debit':'Kredit'}</td><td className="p-2">{a.active?'Aktif':'Nonaktif'}</td><td>{canEdit&&<button className="text-blue-700 underline" onClick={()=>{setOriginalCode(a.code);setAccountEdit({...a});}}>Edit</button>}</td></tr>)}</tbody></table></div>}
      </>}
    </>}
    {show&&book&&<div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4"><form aria-label="Input jurnal umum" className={`${box} w-full max-w-3xl space-y-3 max-h-[90vh] overflow-y-auto`} onSubmit={e=>{e.preventDefault();void run(async()=>{await changeBook(b=>{checkDate(b,date,state.periodClosings);if(lines.some(l=>['1200','1300','1301'].includes(l.account)))throw Error('Persediaan dan aset harus diposting melalui modul stok/aset agar subledger tetap cocok.');appendJournal(b,{source:'manual:'+crypto.randomUUID(),sourceNumber:sourceNumber||'MANUAL',date,description,createdBy:state.currentUser.nama,lines});},'Jurnal umum manual');setShow(false);setDescription('');setSourceNumber('');setLines([{account:'1000',debit:0,credit:0},{account:'4001',debit:0,credit:0}]);});}}><h2 className="font-semibold">Jurnal umum (termasuk pendapatan / pengeluaran)</h2><label className="block text-sm">Tanggal<input required type="date" value={date} className={`${field} block w-full`} onChange={e=>setDate(e.target.value)}/></label><label className="block text-sm">Nomor transaksi sumber<input required className={`${field} block w-full`} value={sourceNumber} onChange={e=>setSourceNumber(e.target.value)}/></label><label className="block text-sm">Keterangan<textarea required className={`${field} block w-full`} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>Akun</th><th>Debit</th><th>Kredit</th><th/></tr></thead><tbody>{lines.map((l,i)=><tr key={i}><td><select aria-label={`Akun baris ${i+1}`} className={`${field} w-full`} value={l.account} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,account:e.target.value}:x))}>{book.accounts.filter(a=>a.active).map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></td>{(['debit','credit'] as const).map(k=><td key={k}><input aria-label={`${k} baris ${i+1}`} type="number" min="0" step="0.01" className={`${field} w-28`} value={l[k]} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,[k]:Number(e.target.value)}:x))}/></td>)}<td><button type="button" disabled={lines.length<=2} onClick={()=>setLines(lines.filter((_,n)=>n!==i))}>Hapus</button></td></tr>)}</tbody></table></div><button type="button" className="text-blue-700" onClick={()=>setLines([...lines,{account:'1000',debit:0,credit:0}])}>Tambah baris</button><p className={balance.difference===0?'text-green-700':'text-red-700'}>Debit {money(balance.debit)} · Kredit {money(balance.credit)} · Selisih {money(balance.difference)}</p><div className="flex justify-end gap-3"><button type="button" disabled={busy} onClick={()=>setShow(false)}>Batal</button><button disabled={busy||balance.difference!==0||balance.debit===0} className="bg-blue-600 text-white px-4 py-2 rounded-lg">Posting jurnal</button></div></form></div>}
    {accountEdit&&book&&<div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4"><form className={`${box} w-full max-w-lg space-y-3`} onSubmit={e=>{e.preventDefault();void run(async()=>{await changeBook(b=>{const old=originalCode?b.accounts.find(a=>a.code===originalCode):undefined;if(!originalCode&&b.accounts.some(a=>a.code===accountEdit.code))throw Error('Kode akun sudah digunakan.');if(!/^\d{4,6}$/.test(accountEdit.code)||!accountEdit.name.trim())throw Error('Kode harus 4–6 digit dan nama wajib diisi.');if(old&&b.journals.some(j=>j.lines.some(l=>l.account===old.code))&&(old.group!==accountEdit.group||old.normal!==accountEdit.normal))throw Error('Kelompok/saldo normal akun yang sudah digunakan tidak boleh diubah.');if(old)b.accounts=b.accounts.map(a=>a.code===old.code?accountEdit:a);else b.accounts.push(accountEdit);},'Master akun');setAccountEdit(null);});}}><h2 className="font-semibold">Master akun</h2><label className="block text-sm">Kode<input required disabled={originalCode!==null} className={`${field} w-full`} value={accountEdit.code} onChange={e=>setAccountEdit({...accountEdit,code:e.target.value})}/></label><label className="block text-sm">Nama<input required className={`${field} w-full`} value={accountEdit.name} onChange={e=>setAccountEdit({...accountEdit,name:e.target.value})}/></label><label className="block text-sm">Kelompok<select className={`${field} w-full`} value={accountEdit.group} onChange={e=>setAccountEdit({...accountEdit,group:e.target.value as AccountGroup})}>{Object.entries(groupNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="block text-sm">Saldo normal<select className={`${field} w-full`} value={accountEdit.normal} onChange={e=>setAccountEdit({...accountEdit,normal:e.target.value as 'debit'|'credit'})}><option value="debit">Debit</option><option value="credit">Kredit</option></select></label><label className="flex gap-2"><input type="checkbox" checked={accountEdit.active} onChange={e=>setAccountEdit({...accountEdit,active:e.target.checked})}/>Aktif</label><div className="flex justify-end gap-3"><button type="button" onClick={()=>setAccountEdit(null)}>Batal</button><button disabled={busy} className="bg-blue-600 text-white px-4 py-2 rounded-lg">Simpan akun</button></div></form></div>}
  </div>;
}
