import { useState } from 'react';
import { useApp } from '../store';
import { useBooks } from '../books';
import { checkDate, postOpeningStock, today, pendingOpeningPrices, verifyOpeningPrice } from '../lib/accounting';
export default function OpeningStock(){
 const {state}=useApp(),{book,busy,changeBook}=useBooks();
 const [item,setItem]=useState(state.barang[0]?.id??''),[warehouse,setWarehouse]=useState(state.gudang[0]?.id??''),[date,setDate]=useState(today()),[qty,setQty]=useState(0),[cost,setCost]=useState(0),[message,setMessage]=useState('');
 if(!book||!['admin','finance'].includes(state.currentUser.role))return null;
 return <><section className="bg-amber-50 border rounded-xl p-4"><h2 className="font-semibold">Verifikasi harga saldo awal — qty tetap</h2><p className="text-sm my-2">Masukkan harga yang sudah diperiksa per satuan dasar. Nilai persediaan dan jurnal modal awal diperbarui tanpa mengubah qty.</p>{pendingOpeningPrices(book).map(m=><form key={m.id} className="flex gap-3 items-center flex-wrap my-3" onSubmit={e=>{e.preventDefault();const input=new FormData(e.currentTarget);void changeBook(b=>verifyOpeningPrice(b,m.id,Number(input.get('cost')),state.currentUser.nama),'Verifikasi harga saldo awal').catch(e=>setMessage(e.message));}}><span>{state.barang.find(x=>x.id===m.itemId)?.nama??m.itemId} / {state.gudang.find(x=>x.id===m.warehouseId)?.nama} · Qty {m.balance}</span><input aria-label="Harga saldo awal terverifikasi" name="cost" required type="number" min="0" step="0.01" placeholder="Harga per satuan dasar" className="border rounded p-2"/><button disabled={busy} className="bg-blue-600 text-white rounded px-3 py-2">Simpan harga terverifikasi</button></form>)}{!pendingOpeningPrices(book).length&&<p className="text-sm">Tidak ada harga saldo awal menunggu verifikasi.</p>}</section><details className="bg-white border rounded-xl p-4"><summary className="cursor-pointer font-medium">Input saldo awal barang tanpa histori</summary><form className="mt-3 flex gap-3 flex-wrap items-end" onSubmit={e=>{e.preventDefault();setMessage('');void changeBook(b=>{checkDate(b,date,state.periodClosings,warehouse);if(!state.barang.some(x=>x.id===item&&x.statusAktif)||!state.gudang.some(x=>x.id===warehouse&&x.statusAktif))throw Error('Barang / gudang tidak aktif.');postOpeningStock(b,item,warehouse,date,qty,cost,state.currentUser.nama);},'Saldo awal stok').then(()=>setMessage('Saldo awal, mutasi, dan jurnal tercatat.')).catch(e=>setMessage(e.message));}}>
 {[['Barang',item,setItem,state.barang.map(b=>[b.id,b.nama])],['Gudang',warehouse,setWarehouse,state.gudang.map(g=>[g.id,g.nama])]].map(([label,value,setter,options])=><label key={String(label)} className="text-sm">{String(label)}<select className="block border rounded p-2" value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}>{(options as string[][]).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>)}
 <label className="text-sm">Tanggal<input required type="date" className="block border rounded p-2" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="text-sm">Qty satuan dasar<input required type="number" min="0.000001" step="0.000001" className="block border rounded p-2 w-32" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label className="text-sm">Harga/unit (Rp)<input required type="number" min="0" step="0.01" className="block border rounded p-2 w-40" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><button disabled={busy} className="bg-blue-600 text-white rounded px-4 py-2">Posting saldo awal</button></form>{message&&<p role="status" className="text-sm mt-3">{message}</p>}</details></>;
}
