import { useState } from 'react';
import { useApp } from '../store';
import OpeningStock from './OpeningStock';
import { useBooks } from '../books';
import { stockBalance, monthEnd, today } from '../lib/accounting';
import { money } from '../lib/finance';
const field='border rounded-lg px-3 py-2 text-sm bg-white';
export default function StockHistory({card=false}:{card?:boolean}) {
  const {state}=useApp(),{book}=useBooks();
  const [item,setItem]=useState(state.barang[0]?.id??''),[warehouse,setWarehouse]=useState(state.gudang[0]?.id??'');
  const [month,setMonth]=useState(state.selectedPeriode);
  const start=month+'-01',end=monthEnd(month);
  const before=new Date(start+'T00:00:00Z');before.setUTCDate(before.getUTCDate()-1);
  const opening=book?stockBalance(book,item,warehouse,before.toISOString().slice(0,10)):null;
  const rows=book?.movements.filter(m=>(!card||m.itemId===item&&m.warehouseId===warehouse)&&m.date>=start&&m.date<=end)??[];
  return <div className="space-y-4"><OpeningStock /><h1 className="text-2xl font-bold">{card?'Kartu Stok':'Mutasi Stok'}</h1><p className="text-sm text-gray-500">Histori mutasi tersimpan · Saldo dan nilai moving average per barang/gudang</p>{!book?<p className="bg-amber-50 p-4 rounded-xl">Aktifkan buku terintegrasi di Jurnal Umum terlebih dahulu.</p>:<><div className="flex flex-wrap gap-3"><label className="text-sm">Periode<input className={`${field} block`} type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>{card&&<><label className="text-sm">Barang<select className={`${field} block`} value={item} onChange={e=>setItem(e.target.value)}>{state.barang.map(b=><option key={b.id} value={b.id}>{b.nama}</option>)}</select></label><label className="text-sm">Gudang<select className={`${field} block`} value={warehouse} onChange={e=>setWarehouse(e.target.value)}>{state.gudang.map(g=><option key={g.id} value={g.id}>{g.nama}</option>)}</select></label></>}</div>{card&&<p className="bg-blue-50 p-4 rounded-xl text-sm">Saldo awal {opening?.balance??0} · Nilai awal {money(opening?.valueBalance??0)} · Harga rata-rata {money(opening?.average??0)}</p>}<div className="bg-white border rounded-xl p-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Tanggal','No transaksi',...(!card?['Barang / Gudang']:[]),'Jenis / Keterangan','Masuk','Keluar','Saldo','Harga/unit','Nilai masuk','Nilai keluar','Nilai saldo','Rata-rata'].map(h=><th key={h} className="p-2 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{rows.map(m=><tr key={m.id} className="border-t"><td className="p-2 whitespace-nowrap">{m.date}</td><td className="p-2">{m.number}</td>{!card&&<td className="p-2">{state.barang.find(b=>b.id===m.itemId)?.nama??m.itemId}<p className="text-xs">{state.gudang.find(g=>g.id===m.warehouseId)?.nama}</p></td>}<td className="p-2 min-w-48">{m.type}<p className="text-xs text-gray-500">{m.description}</p></td>{[m.inQty,m.outQty,m.balance].map((n,i)=><td key={i} className="p-2 text-right">{n}</td>)}{[m.unitCost,m.inValue,m.outValue,m.valueBalance,m.average].map((n,i)=><td key={i} className="p-2 whitespace-nowrap">{money(n)}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="py-5 text-gray-500">Belum ada mutasi pada periode ini.</p>}</div></>}</div>;
}
export function UsagePage() {
  const {state}=useApp(),{book,busy,error,postUsageRecord}=useBooks();
  const [date,setDate]=useState(today()),[item,setItem]=useState(state.barang[0]?.id??''),[warehouse,setWarehouse]=useState(state.gudang[0]?.id??''),[qty,setQty]=useState(0),[unit,setUnit]=useState(''),[description,setDescription]=useState(''),[message,setMessage]=useState('');
  const master=state.barang.find(b=>b.id===item),activeUnit=unit||master?.satuanDasar||'';
  const balance=book?stockBalance(book,item,warehouse):null;
  return <div className="space-y-4"><h1 className="text-2xl font-bold">Pemakaian Bahan</h1><p className="text-sm text-gray-500">Posting mengurangi stok dan persediaan serta mendebit Beban Bahan Laundry.</p>{error&&<p role="alert" className="bg-red-50 text-red-800 p-4">{error}</p>}{message&&<p role="status" className="bg-green-50 text-green-800 p-4">{message}</p>}<form className="bg-white border rounded-xl p-4 space-y-3 max-w-2xl" onSubmit={e=>{e.preventDefault();setMessage('');void postUsageRecord({id:'PK-'+crypto.randomUUID(),date,itemId:item,warehouseId:warehouse,quantity:qty,unit:activeUnit,description}).then(()=>{setMessage('Pemakaian, mutasi, dan jurnal tersimpan bersama.');setQty(0);setDescription('');}).catch(()=>{});}}><label className="block text-sm">Tanggal<input required type="date" className={`${field} block w-full`} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block text-sm">Barang<select className={`${field} block w-full`} value={item} onChange={e=>{setItem(e.target.value);setUnit('');}}>{state.barang.filter(b=>b.statusAktif).map(b=><option key={b.id} value={b.id}>{b.nama}</option>)}</select></label><label className="block text-sm">Gudang<select className={`${field} block w-full`} value={warehouse} onChange={e=>setWarehouse(e.target.value)}>{state.gudang.map(g=><option key={g.id} value={g.id}>{g.nama}</option>)}</select></label><p className="text-sm">Stok tersedia {balance?.balance??0} {master?.satuanDasar} · Rata-rata {money(balance?.average??0)}</p><div className="flex gap-3"><label className="block text-sm flex-1">Qty<input required type="number" min="0.000001" step="0.000001" className={`${field} block w-full`} value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label className="block text-sm">Satuan<select className={`${field} block`} value={activeUnit} onChange={e=>setUnit(e.target.value)}>{[...new Set([master?.satuanDasar,...(master?.konversi.map(k=>k.fromUnit)??[])])].filter(Boolean).map(u=><option key={u}>{u}</option>)}</select></label></div><label className="block text-sm">Keterangan<textarea required className={`${field} block w-full`} value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={!book||busy||!['admin','finance'].includes(state.currentUser.role)} className="bg-blue-600 text-white px-4 py-2 rounded-lg disabled:opacity-50">Posting pemakaian</button>{!book&&<p className="text-amber-800">Aktifkan buku di Jurnal Umum terlebih dahulu.</p>}</form></div>;
}
